### ISSUE TITLE
[Crash-Compat] issue with newest version of Energy Control

### ISSUE THREAD

**Issue by gatoborrachon** [Su5eD/GregTech-Experimental#21] opened 2021-02-18 22:16 UTC
**Describe the bug**
Crash at startup when using EnergyControl-1.12.2-0.1.9 (released yesterday)

**Does this bug cause a crash?**
https://pastebin.com/RDK5AhEG

**Side**
Does this bug occur on a Client, or a Server?
Client (i guess)

**To Reproduce**
1. Add Energy Control 0.1.9 and GregTech 1.0-28 and try to load Minecraft
2. See error.

**Expected behavior**  
Crash at startup

**Additional context**  
-I noticed about this yesterday, but i had no time to prove it (run an instance with Energy Control and GregTech only).
-Tell me if i need to open an Issue on EnergyControl if this is their fault (it does not happen with EnergyControl-1.12.2-0.1.8).

EDIT: Now that i think about it, i will open an issue on their side,

**Comment by Su5eD** [comment] 2021-02-18 22:29
The issue is on my side. `com.zuxelus.energycontrol.api.EnergyContolRegister` had a grammar mistake in its name, and since it has been fixed now, the class can't be found. Updating the EC dependency should solve this.

**Comment by gatoborrachon** [comment] 2021-02-18 23:08
ok, i will close this (and the other) issue as soon as a new .jar is released and there are not issues, many thanks

**Closed as completed** 2021-03-24 07:31 UTC
Labels: bug 🐞
